jameshughes89/cs4XX-EvolutionaryComputation

site/conf.py
Ran the formatter and it cleaned up the conf file
=> run format

site/index.rst, site/topics/intro/intro.rst
Make the existing content about the EC course. It was about cs101 since that is where it was copied from.
=> Make existing content about the course

site/outline/outline.rst
Update the Outline as much as possible for Fall 2023. 
The evaluations part is TBD at this stage as I have no plan yet.
=> Outline --- Fall 2023

site/outline/outline.rst
Add CSCI 340 specific details to the outline. 
This will be updated once I have a plan for the course.
=> Outline --- 340 specific content

site/index.rst
Add the problems topic to the index so it is reachable.
=> Problems topic --- Add to index

src/crossover.py, src/mutation.py, test/test_crossover.py, test/test_mutation.py
Inversion mutation. 
Also snuck in changes of "point" to "index".
=> Inversion mutation

src/crossover.py, test/test_crossover.py
=> Order crossover

src/selection.py, test/test_selection.py
Roulette wheel selection and tests.
=> Roulette wheel selection

src/selection.py, test/test_selection.py
=> Make tournament selection work on minimization problems 

src/ga_n_queens.py, test/test_ga_n_queens.py
=> Simple GA for n queens

src/ga_max_bitstring.py
Calculate the fitness values after the last set of genetic operators.
=> Check the fitness values AFTER generations

setup.py, src/pso.py, test/test_pso.py
=> Write Pso algorithm

setup.py, src/ga_max_bitstring.py
Add lists to keep track of the max fitness value and the average fitness values for each generation. 
For teaching
=> Add bookkeeping lists to the bitstring GA

setup.py, src/ga_max_bitstring.py
:new: :mortar_board: :eyes: 
Filled in some subtopics for simple GA topic
Wanted to contribute, hopefully can use ideas as springboard
Only updated ``.rst'' file with text, hopefully doesn't break anything
=> Fill in simple-ga subtopics

src/ga_max_bitstring.py
remove duplicate variable `population_fitness`
=> Bitstring GA --- Remove duplicate unused var

site/topics/genetic-algorithms/simple-ga.rst, src/ga_max_bitstring.py
Introduce the topic and problem. 
Add tags to the code for easier reference.
=> Topic bitstring GA --- Intro and Problem description 

src/ga_max_bitstring.py
=> Code bitstring ga --- tweak params and plots

site/topics/genetic-algorithms/simple-ga.rst
Change the key ideas (chromosome, population, etc.) to bold face instead of italics (at least for its first occurrence). 
@VeiledTee recommended it and I liked it. Sure italics emphasizes things, but BF is a little punch-ie-er for the key concepts.
=> Topic bitstring ga --- Change key concepts to boldface

site/index.rst, site/topics/origin/origin.rst
Adding the section that explains how there is no point to anything. 
This one is kinda' tricky as I don't think people can truly appreciate these ideas unless they spend some time thinking about them on their own. Either way, I think this will hopefully hit the point.
=> 🎓 Origin topic --- Invisible hand 

site/topics/representation/representation.rst
Create the section titles for the rep topic
Makes later PRs easier to merge if topic is made with multiple PRs. 
YOLO
The original course notes has this topic combined with the generic operator topic. Although it makes sense to combine them (see the rep, then talk about the generic operators), I see value in keeping them their own topics (ease of finding details and can focus more on discussions related to rep).
=> :mortar_board: Representation Topic --- Layout :microscope: 

site/topics/intro/intro.rst
1. Remove the readings for "for next class"
2. high level -> high-level
3. Make sentence start with bullet point
1. They were from 162
2. It's more correct I think
3. I like points
:+1: Built local, looks good
=> :lipstick: Intro topic --- Remove readings and small cleanup :microscope: 

site/topics/overview/overview.rst
Create the layout for the overview topic 
Makes merging easier later 
YOLO
=> :mortar_board: Overview topic --- Layout :microscope: 

site/topics/overview/overview.rst
Mention various popular/common types of EAs/EC. 
:+1: built local, looks good
=> :mortar_board: Overview topic --- Types of EAs

site/index.rst
Add topic to index 
So it can be found 
:+1: built local, looks good
=> 🎓 Overview topic --- Add topic to index 🔬 

site/topics/representation/representation.rst
Intro bit to the representation topic 
Yolo
=> :mortar_board: Topic representation --- Intro topic :microscope: 

site/topics/genetic-algorithms/n-queens-ga.rst
1. Create the layout for the topic
2. Add the intro 
Layout was copy/paste from the other ga implementation topic 
No way jose
=> :mortar_board: Topic n queens --- Layout and intro 

site/topics/genetic-algorithms/n-queens-ga.rst
Explain the problem for the millionth time 
Although it's been explained before, given the topic, it is still good to re-explain 
:+1:
=> :mortar_board: Topic n queens GA --- Explain problem 

site/topics/genetic-algorithms/n-queens-ga.rst
Discuss the rep and creation of the chromosomes and population 
:+1:
=> :mortar_board: Topic n queens GA --- initialization section 

site/topics/genetic-algorithms/n-queens-ga-experiment.rst
Create the layout for the topic
=> :mortar_board: Topic n queens experiments --- Layout 

site/topics/genetic-algorithms/n-queens-ga-experiment.rst, site/topics/genetic-algorithms/n-queens-ga.rst, site/topics/genetic-algorithms/simple-ga-experiment.rst, site/topics/genetic-algorithms/simple-ga.rst
As brought up in #88 
1. Mention to either fork or download the scripts and do setup
2. Replace "for next class" wording to emph that they are just to check out those specific scripts
1. To help. Forking really probably will be the easiest way to do it. 
2. Will help emphasize that forking is easier 
:+1:
These topics where the notes are included will be instructed like a directed lab (at least for that part of the topic). In other words, the note, although it includes proper links to the relevant details, will be accompanied with instruction from me to help with any confusion.
=> :lipstick: Setting up code --- Create note for forking

site/topics/genetic-algorithms/n-queens-ga-experiment.rst
Have them change out the selection and genetic operators and see what happens. Also encourage them to be creative and come up with their own wacky ideas. 
great way to learn 
:-1:
=> :mortar_board: Topic n queens experiment --- Change out operators

site/topics/genetic-operators/genetic-operators.rst
Layout for the genetic operators topic
:-1:
=> :mortar_board: Topic genetic operators --- Layout :microscope: 

site/topics/genetic-algorithms/n-queens-ga-experiment.rst
Task for changing out the rep (and fitness and operators)
More tinkering experience and seeing direct results/impact of changes. 
After writing this one, I am wondering if it really adds value. I'm on the fence. On one hand, I think just taking the time to make makes changes to the existing code, swapping out a fitness function, rep, and operators is good. On the other, idk if this adds enough value when considering the amount of work this task requires, especially after already establishing how bad the other reps are. Idk, I could go either way.
=> :mortar_board: :question: Topic n queens experiment --- Change rep task 

site/index.rst
Add link to topic to index
:+1:
=> :mortar_board: Topic n queens experiments --- Add to index :microscope: 

site/topics/genetic-operators/genetic-operators.rst
Introduce the genetic operators topic 
👎
=> 🎓 Topic genetic operators --- Introduce topic 

site/topics/genetic-operators/genetic-operators.rst
Mention genetic operators for integer representations 
:+1:
1. I originally didn't bother with the subsections "Crossovers" and "Mutations" since there was not much to talk about, but I opted to add it back because (a) it is consistent and (b) the subsections are added to the side bar for easy navigation. 
2. I will probably add figures later. Just not a priority right now.
=> :mortar_board: Topic genetic operators --- Integer Representations 

site/index.rst
=> :mortar_board: Topic genetic operator --- Add to index :microscope: 

site/topics/selection/selection.rst
General layout for the selection topic
=> :mortar_board: Topic selection --- Layout :microscope: 

site/topics/particle-swarm-optimization/problems.rst
=> :mortar_board: Topic PSO --- Layout :microscope: 

site/topics/genetic-programming/genetic-programming.rst
Layout for topic about GP 
I used to call it "Bloat --- Survival of the _Fattest_", but that's prob not cool.
=> :mortar_board: Topic genetic programming --- Layout :microscope: 

site/topics/problems/multi-objective.rst
Multi-objective problem topic layout
=> :mortar_board: Topic Multi-objective problems --- Layout :microscope: 

site/topics/selection/selection.rst
=> :mortar_board: Topic selection --- Introduction :microscope: 

site/index.rst
Add to index 
:+1: AND something is wrong. 
For some reason, it did not add a number nor was it added to the side nav bar. 
I tinkered with it, and even adding other topics, and removing topics, it would not update the numbering. I even deleted the whole build and nothing... Even telling it not to number it will still be numbered. 
I will sub the PR, check the artifact, and regardless, merge. The content is important and the numbering can be looked into later. The only thing I could think of is the sphinx update I did, but who knows. That's an issue for another day (will make an issue).
=> :mortar_board: Topic selection --- Index :microscope: 

site/topics/genetic-programming/genetic-programming.rst
Explain the breast cancer problem 
Easy motivation for GP, which is the topic 
:+1:
=> :mortar_board: Topic genetic programming --- Breast cancer problem 

site/topics/selection/selection.rst
Remove the section for rank based and make it a subsection in the proportional section
:+1:
=> :mortar_board: Topic selection --- Mention rank based selection 

site/topics/genetic-programming/genetic-programming.rst
Introduce the GP topic 
:+1: 
There is still the weird numbering issues with local builds though, which is odd since it's fine in the action which uses the same sphinx version
=> :mortar_board: Topic genetic programming --- Introduction :microscope: 

site/index.rst, site/outline/outline.rst
Put in the correct time and place for the lectures and for office hours.
=> :bug: Outline and Index --- Update times and place :microscope: 

site/topics/genetic-programming/genetic-programming.rst
Discuss the noteworthy differences in the setup
:+1: 
I actually removed some stuff I was going to mention, like how the trees are made and the GP selection, but I opted to ignore since this can get complex and is't outside the scope of the course; it's not a course on GP.
=> :mortar_board: Topic genetic programming --- Typical setup 

site/topics/genetic-programming/symbolic-regression-gp.rst
Create the layout for the symbolic regression topic. Also include a short intro and the "for next time" bit.
=> :mortar_board: Topic symbolic regression example --- Layout, intro, and TODO

site/topics/genetic-programming/symbolic-regression-gp.rst
=> :mortar_board: Topic symbolic regression --- DEAP 

site/conf.py
Run format on the configuration file 
Forgot to before I guess. 
I assumed this would have failed some checks on github actions, but I guess not, whatever.
=> :lipstick: Conf file --- Format :microscope: 

src/gp_symbolic_regression.py
#143 
kinda #147 
Actually use the constants in the code for the genetic operator rates 
I forgot
:+1:
=> :mortar_board: :bug: Symbolic regression --- Use genetic operator constants :microscope: 

site/topics/genetic-programming/symbolic-regression-gp.rst
Show the command to run and also explain what to expect when you get results 
So they know how to run.
Also, the output can be intimidating or just weird if you do not expect it. 
:+1:
=> :mortar_board: Topic symbolic regression --- Show how to run and look at results

site/topics/genetic-algorithms/simple-ga-experiment.rst
=> typo GA experience

site/index.rst
=> :mortar_board: Topic symbolic regression --- Add to index :microscope: 

site/assignments/tsp.rst
Create the general layout for the assignment description 
:+1: 
It may change as I fill it in, but this is a good staring point.
=> :mortar_board: Assignment TSP --- Layout 

site/topics/genetic-algorithms/simple-ga-experiment.rst
Add new section title for last few activities 
Felt like it should be there.
=> 💄 Topic simple ga experiment --- Add new section title 🔬 

site/assignments/tsp.rst
Explain the data files. 
Previous years I just told them to go find instances and figure it out. This always created some issues for some, so I figured, I'll simplify this. 
Perhaps there's an argument for making them _figure it out_, but whatever. 
I also like the JSON format better vs. the weird and inconsistent "tsplib" format. 
:+1: 
When I converted to JSON, I did try to store the data in matrices, but they were too chonky
=> :mortar_board: Assignment TSP --- Describe the data files 

site/assignments/tsp.rst
Provide a high-level idea of how the "points" will be awarded. 
:+1:
=> :mortar_board: Assignment TSP --- High level mark/points breakdown 

site/assignments/tsp.rst
Describe implementing the GA for TSP. Also explain the additional things they can do for more points. 
:+1:
=> :mortar_board: Assignment tsp --- Implementation section 

site/assignments/tsp.rst
Just tell them to submit stuff via Moodle
=> :mortar_board: Assignment tsp --- Submission details :microscope: 

site/assignments/tsp/tsp.rst
Point out what the GA should have, at a minimum
=> 🎓 Assignment tsp --- Emphasize what they need in the GA 🔬 

site/assignments/tsp/tsp.rst
Make it clearer that points are awarded only if the corresponding task is completed sufficiently. 
Always assume there is a student that will try to game you.
Add warning and make sure each task is described in a way where there is no guarantee. 
:-1: YOLO
Marker will be generous either way. This just hedges against students who think (a) they are lawyers and assignment descriptions are (b) legally binding contracts.
=> :mortar_board: Assignment tsp --- Emphasize that points may not be awarded :microscope: 

site/topics/parameters/comparing.rst
Explain the null hypothesis and why it kinda' matters. 
It helps frame the logic behind wtf a permutation test actually is
:+1: 
It's the end of the day, and although I think I explained it well, it's possible it's not clear.
=> :mortar_board:  Topic comparing --- Null hypothesis 

site/topics/representation/representation.rst
permutation -> Permutation 
Consistency. It bothers me as a lower case p
=> :mortar_board: :lipstick: Topic representation --- p -> P :microscope: 

site/index.rst, site/topics/parameters/comparing.rst
Feedback in #200 
Clean up content and add to index 
Not all points in #200 are addressed. Not sure yet if I want to include all feedback yet as it may make things less clear to the students.
=> 🎓 Topic comparing --- Clean based on stats guy's feedback 🧹 

site/student-lectures/description.rst
1. Clean up
2. Add more details (dates, how to submit)
3. Mark what has been selected
=> :lipstick: :mortar_board: Student lectures --- Clean/more details

site/assignments/gp/gp.rst
1. Copy the assignment description from the GA
2. Make small changes to make it about GP
3. Remove the GA heavy description sections
4. Update section titles
5. Small changes to the report part as it's effectively identical to the GA one (just switched to GP and SR where necessary)
=> :mortar_board: Assignment GP --- Copy template and small changes 

site/student-lectures/description.rst
Remove novelty search and cultural algos and both of the Nov 14th dates. 
A studentS picked the date.
=> :mortar_board: Student lectures --- Remove novelty search & cultural algos and date :microscope: 

site/topics/problems/multi-objective.rst
Discuss scalarization and weighted sums
Kept brief as it's quite straight forward, simple to do, and works well in many cases. 
:+1:
=> :mortar_board: Topic multi objective --- Scalarization

site/student-lectures/description.rst
Remove more topics and dates. 
Choices are coming in.
=> Student lectures --- Update topics and dates more 

site/student-lectures/description.rst
=> Lectures --- Remove more topics and dates 

site/student-lectures/description.rst
=> Lectures --- Remove last date :microscope: 

site/index.rst, site/topics/particle-swarm-optimization/pso.rst
1. Show the idea of the algo
2. Show how it's basically just a GA (but don't tell anyone)
3. Discuss some ideas that could be thrown at the algo 
👍 
I feel like I am using the wrong word, but my brain is ded as I am working while at home with a sick toddler. I don't think the right word is "exponential decay".  I am thinking of like a sigmoid function where the velocity approaches some speed. If you think of a better word, let me know. 
> 
* Velocity clamping
* Disallow particles from having velocities over a certain value
* This could be done by setting a ceiling, or an exponentially decaying velocity
=> 🎓 Topic pso --- Show also pseudocode and discuss some enhancements 

site/topics/genetic-programming/genetic-programming.rst
Remove the extra "above" 
It was silly the way it was
Because i wasn't sure which "above" to remove, I asked ChatGPT to rewrite it for me. This is what it gave me 
> Examine the preceding program or function for the breast cancer identification issue
=> :bug: Topic genetic programming --- Remove extra 'above' :microscope: 

site/student-lectures/Memetic-Algorithms/Memetic-Algorithms.rst
Memetic algorithm lecture was not shwoing in the index. Updated rst topics to align with indexing
Memetic algorithm lecture was not shwoing in the index.
Student lecture - Memetic algorithm
=> Updated indexing for memetic algorithm lecture

site/student-lectures/Differential_Evolution/Differential_Evolution.rst
=> Updating typo

site/student-lectures/Evolutionary_Art/evolutionary_art.rst
Bekker Lecture
Changed some numbered points to unnumbered points as well as added on grammatical change
Looks slightly better
evolutionary_art.rst
Tested
=> Bekker Lecture update

site/assignments/tsp/tsp.rst
Add due date for assignment 1
YOLO
=> :mortar_board: Assignment 1 --- Fall 2024 Due Date

site/topics/overview/overview.rst
Fix typo
"is is" -> "be is"
Nah
=> :mortar_board: :bug: Topic overview --- Typo is is -> be is

site/student-lectures/description.rst
Mark some topics as taken
1. Artificial Immune Systems
2. Evolutionary Art
3. Coevolution
Students picked them 
Nah
=> :mortar_board: Student lectures --- Artificial Immune Systems, Evo Art, Coevolution taken :microscope: 

site/topics/overview/overview.rst
:new: :bomb: :mortar_board: :memo: :robot: :lipstick: :bug: :telescope: :art: Add relevant emojis to title. [See style guide.](https://github.com/jameshughes89/cs101/blob/main/CONTRIBUTING.md#style-guidelines).
N/A
Change the word "distinctive" to "destructive."
Original word doesn't get intended point across. 
Section 6.2.5.1 Mutation. (site/topics/overview/overview.rst) 
modify relevant line in site/topics/overview/overview.rst file.
N/A
N/A
=> :new: :mortar_board: :bug: Change distinctive to Destructive

site/student-lectures/description.rst
Neuroevolution is taken
Neuroevolution is taken
=> i want that.rst

site/student-lectures/description.rst
Student Lecture on Self-Organization
=> I want this topic for the Student Lecture

site/student-lectures/description.rst
A student (myself) wants to pick (Memetic Algorithm)
Before someone else takes it.
Student lecture region of the website
=> 🎓  Student Lectures --- Set Memetic Algorithms to taken

site/student-lectures/description.rst
I want to do Differential Evolution
=> Student lectures --- Set Differential Evolution to taken

site/assignments/gp/gp.rst
=> :mortar_board: Assignment GP --- Due date Fall 2024

site/assignments/gp/gp.rst
Remove old information 
This information presumably only pertains to previous years of the class (new due date is after reading week)
Assignment 2: Genetic Programming (http://modsurski.com/csci340/assignments/gp/gp.html)
=> :bomb: :mortar_board: Remove old assignment information

site/assignments/gp/gp.rst
Move due date back 1 week. 
We're moving slowly this year in the content.
=> :mortar_board: Assignment GP --- Move due date back 1 week :microscope: 

site/topics/selection/selection.rst
Fix typo in lamba symbol
Stochastic Universal Selection in Section 11
=> 🎓 🐛 Fix lamba symbol render 

site/student-lectures/description.rst
:new: :bomb: :mortar_board: :memo: :robot: :lipstick: :bug: :telescope: :art: Add relevant emojis to title. [See style guide.](https://github.com/jameshughes89/cs101/blob/main/CONTRIBUTING.md#style-guidelines).
Student Lecture
Marks
in class?
=> Take Artficial Life Lecture

site/topics/genetic-programming/genetic-programming.rst
Fix 'typed' vs 'types' spelling mistake
To get Famous on github. also, to provide others with a better learning experience :smiling_face_with_tear:
GP lecture
=> Update grammar genetic-programming.rst

site/assignments/gp/gp.rst, site/assignments/pso/pso.rst
1. Push GP assignment back 1 week... AGAIN
2. Add due date for PSO
Things are moving to slow in lecture, and idk why. This semester doesn't seem right...
=> :mortar_board: Assignments GP and PSO --- Update/add due date :microscope: 

site/student-lectures/description.rst
Update list on what has been selected after I changed things up
Also, order the topics alphabetically
=> :lipstick: Lectures --- Update list and reorder list :microscope: 

site/student-projects/description.rst
Set date on when topic needs to be picked by 
Also change a 2023 -> 2024
=> :mortar_board: Project --- Set date for topic selection :microscope: 

site/student-lectures/description.rst
=> :mortar_board: Student lectures --- Add days :microscope: 

site/student-lectures/description.rst
Add student initials to dates.
=> 🎓 Lectures --- Add students to dates

.gitignore
Found some "OS generated files" to add to the ignore list. 
ds_store popped up from students. ~Still not sure what ds store is, but whatever.~ Don't want these files in the repo. 
Found a gitignore with some things to ignore. 
@twentylemon brought this point up offline, which is a great idea.
=> 💄 gitignore --- add some files to ignore

site/topics/representation/representation.rst
:new: :bomb: :mortar_board: :memo: :robot: :lipstick: :bug: :telescope: :art: Add relevant emojis to title. [See style guide.](https://github.com/jameshughes89/cs101/blob/main/CONTRIBUTING.md#style-guidelines).
If applicable, replace this text with links to issues and other PRs. [Link with a keyword if you can.](https://docs.github.com/en/issues/tracking-your-work-with-issues/creating-issues/linking-a-pull-request-to-an-issue)
Replace this text with a detailed description of what the change is.
Replace this text with a detailed description of why this is important.
Replace this text with a detailed description of where the change is and why (should it be an aside?).
Replace this text with a detailed description of how it is addressed.
If applicable, replace this text with a detailed …
=> Fix typo in representation.rst: corrected "tree so not" to "trees do not"

site/student-projects/description.rst
Add student initials and topic to schedule.
=> :mortar_board: Project --- Student topic for Dec 1 :microscope: 

site/student-projects/description.rst
Add student initials and topic to their selected date.
=> :mortar_board: Project --- Student topic for Nov 21 :microscope: 
